### ISSUE TITLE
Impossible to create log file

### ISSUE THREAD

**Issue by karfam** [ech0s7r/androidlog#3]
Having exception with the export to csv file

**Kotlin 1.3.70**
**Lintoptions enabled**

Init Log Function
```private fun initLog() {
        LoggerConfigurator.init(
            Logger.Level.WARN,  /* Minimum level to log */
            123,  /* Application ID */
            "AndroidLogApp",  /* Application name */
            BuildConfig.VERSION_NAME,  /* Application version */
            "123456789",  /* Device ID */
            "AndroidLogApp.log"
        ) /* File name prefix */
        LoggerConfigurator.addAppender(LogcatAppender(LogcatLayout()))
        LoggerConfigurator.addAppender(FileAppender(applicationContext, CsvLayout()))
    }
```
**And here is the logcat**

```E/AndroidLogApp: Impossible to create log file, path=/storage/emulated/0/logs/AndroidLogApp
E/AndroidLogApp: java.io.FileNotFoundException: /storage/emulated/0/logs/AndroidLogApp/AndroidLogApp.log20200309: open failed: ENOENT (No such file or directory)
 at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.io.FileWriter.<init>(FileWriter.java:107)
        at com.ech0s7r.android.log.service.WriterService.f(SourceFile:150)
        at com.ech0s7r.android.log.service.WriterService.a(SourceFile:45)
        at com.ech0s7r.android.log.service.WriterService$b.run(SourceFile:67)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7419)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235) 
        at java.io.FileWriter.<init>(FileWriter.java:107) 
        at com.ech0s7r.android.log.service.WriterService.f(SourceFile:150) 
        at com.ech0s7r.android.log.service.WriterService.a(SourceFile:45) 
        at com.ech0s7r.android.log.service.WriterService$b.run(SourceFile:67) 
```

**Comment by karfam** [comment]
https://developer.android.com/reference/android/os/Environment

**getExternalStorageDirectory()
This method was deprecated in API level 29. To improve user privacy, direct access to shared/external storage devices is deprecated. When an app targets Build.VERSION_CODES.Q, the path returned from this method is no longer directly accessible to apps. Apps can continue to access content stored on shared/external storage by migrating to alternatives such as Context#getExternalFilesDir(String), MediaStore, or Intent#ACTION_OPEN_DOCUMENT.**

**class LoggerConfigurator line 31**
APP_DIR_PATH = Environment.getExternalStorageDirectory().getAbsolutePath() + "/logs/" + APP_NAME;

**Comment by uc-Pri** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
Prashanth-K-Narasimhan, @goto2035, @abitrolly, @kivS, @pecpwee, @daronco, @overtunned, @ocolluphid, @doniyor2109, @zheung, @malolans, @rogosprojects, @kela23, @shved, @Lakshmivallala, @isfull, @toto-castaldi, @bmedicke, @abdqeb, @vinayakgarg20
